spring.application.name=guys
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Guys_db
spring.datasource.username=postgres
spring.datasource.password=postgres
